version: '3.9'
services:
  postgres:
    container_name: pg_container
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'mnpl'
      POSTGRES_USER: 'mnpl'
      POSTGRES_PASSWORD: 'mnpl'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
